language: cpp

sudo: required

matrix:
  include:
    - os: osx
      compiler: clang
      addons:
        apt:
          packages:
            - python3
            - doxygen
    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
            - doxygen
      env: COMPILER=g++-5
    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-6
            - cmake
            - cmake-data
            - doxygen
      env: COMPILER=g++-6
    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
          packages:
            - clang-3.6
            - cmake
            - cmake-data
            - doxygen
      env: COMPILER=clang++-3.6
    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
          packages:
            - clang-3.7
            - cmake
            - cmake-data
            - doxygen
      env: COMPILER=clang++-3.7

before_script:
  - cmake --version
  # install Simgrid dependencies
  - sudo apt-get install libboost1.48-all-dev libboost-graph1.48-dev libboost-graph-parallel1.48-dev libboost-iostreams1.48-dev libboost-math1.48-dev libboost-program-options1.48-dev libboost-python1.48-dev libboost-signals1.48-dev libboost-thread1.48-dev libboost-wave1.48-dev
  # install Simgrid
  - wget https://gforge.inria.fr/frs/download.php/file/36384/SimGrid-3.14.159.tar.gz
  - tar xf SimGrid-3.14.159.tar.gz
  - cd SimGrid-3.14.159 && cmake . && make && sudo make install
  # install Lemon
  - wget http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz
  - tar -xvf lemon-1.3.1.tar.gz
  - cd lemon-1.3.1 && cmake . && make && sudo make install

script:
  - mkdir build && cd build
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..
  - make

notifications:
  email:
    on_success: change
    on_failure: change