language: cpp

sudo: required

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install simgrid
  - wget http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz
  - tar -xvf lemon-1.3.1.tar.gz
  - cd lemon-1.3.1 & mkdir build & cd build & cmake .. & sudo make install
  - cd ../.. & rm -rf lemon*
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..

script: make

notifications:
  email:
    on_success: change
    on_failure: change