language: cpp

sudo: required

matrix:
  include:
    - os: osx
      compiler: clang
      addons:
        apt:
          packages:
            - python3
            - doxygen
    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - g++-5
            - cmake
            - cmake-data
            - doxygen
            - libboost-all-dev
      env: COMPILER=g++-5
    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - g++-6
            - cmake
            - cmake-data
            - doxygen
            - libboost-all-dev
      env: COMPILER=g++-6
    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - clang-3.6
            - cmake
            - cmake-data
            - doxygen
            - libboost-all-dev
      env: COMPILER=clang++-3.6
    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - clang-3.7
            - cmake
            - cmake-data
            - doxygen
            - libboost-all-dev
      env: COMPILER=clang++-3.7

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3 doxygen; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - cmake --version
  # install MSG_Simulation
  - wget https://gforge.inria.fr/frs/download.php/file/36384/SimGrid-3.14.159.tar.gz
  - tar xf SimGrid-3.14.159.tar.gz
  - cd SimGrid-3.14.159 && cmake . && make && sudo make install && cd ..
  # install Lemon
  - wget http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz
  - tar -xvf lemon-1.3.1.tar.gz
  - cd lemon-1.3.1 && cmake . && make && sudo make install && cd .. 

script:
  - mkdir build && cd build
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..
  - make

notifications:
  email:
    on_success: change
    on_failure: change